### ISSUE TITLE
demo scenes use TMP but its not part of package dependencies

### ISSUE THREAD

**Issue by Ale1** [starikcetin/Eflatun.SceneReference#100]
Some demo scenes use `TextMeshPro - Text (UI)` component.  These work fine if TextMeshPro package is already installed in your project.  however, if missing the package, those components will be missing. 

if SceneReference Package is added TMP as part of dependencies, it could be weird to be forced to install TMP for a package that doesnt deal with UI. 
But if demo scenes are modified to use regular text component as it should be sufficient?

**Comment by starikcetin** [comment]
The sandbox project (the project used for developing the package, at the root of this repo) itself has TMP, so it should be fine. I would not want to add it as a dependency to the package though. I did not envision any of the demo scenes to be used outside the sandbox project. Is there a need for it?

**Comment by Ale1** [comment]
Ahhh, sorry. you are right.  Had a mind-fart and forgot that the demo scenes arent part of the package.  ;-P
