### ISSUE TITLE
Error upon install with missing namespace UnityEditor.SettingsManagement

### ISSUE THREAD

**Issue by Wobling** [starikcetin/Eflatun.SceneReference#106]
Hi, 

I tried to install the package manually rather than via the package manager. I got errors stating that UnityEditor.SettingsManagement namespace could not be found. I did a quick search and this appaears to be apart of the ProBuilder package.

As I'm working on a 2D project I don't have that so am I correct in thinking this package has a dependency on it or is UnityEditor.SettingsManagement from another package?

Thanks

**Comment by Ale1** [comment]
Hi Wobling.  The UnityEditor.SettingsManagement is not a special dependency, its just part of the Unity Editor.  i.e, it has nothing to do with the ProBuilder package and that is not a dependency.  
Perhaps the manual installation might have messed something up :-(.
Could you try recreating the issue?  ->  creating a new project from scratch and  installing the SceneReference directly from the package manager?

**Comment by starikcetin** [comment]
How exactly did you do the manual install?

**Comment by starikcetin** [comment]
Hello @Wobling, any updates on this?

**Comment by Wobling** [comment]
> Hello @Wobling, any updates on this?

Hey, sorry I've not had time. I will try to get to it today/tomorrow to get you the answers.

**Comment by starikcetin** [comment]
I am closing this until further information is provided.
