### ISSUE TITLE
I am getting a EmptySceneReferenceException on webgl build

### ISSUE THREAD

**Issue by Buffoverflow** [starikcetin/Eflatun.SceneReference#107]
I am getting a EmptySceneReferenceException on a webgl build.

It works perfectly on Editor.

The Secene references are on a Scriptable object.

Unity 2021.3.34f1

EmptySceneReferenceException: [Eflatun.SceneReference] The SceneReference is empty (not assigned anything). To fix this, make sure the 'SceneReference' is assigned a valid scene asset.

![image](https://github.com/user-attachments/assets/98270e96-ba2b-4589-b594-0f80f0827161)
![image](https://github.com/user-attachments/assets/6377dfe8-b355-4b05-91f2-6eeced550b68)

The list I use in runtime is the Random Scene List.

I am using Odin Serializer, not sure if its related

**Comment by starikcetin** [comment]
I am also seeing some other errors in the log you shared. Please provide the full log.

**Comment by Buffoverflow** [comment]
Here is the full log: 
[localhost-1724772740593.log](https://github.com/user-attachments/files/16764583/localhost-1724772740593.log)

The Odin version I am using is 3.3.1.5

As you can see on the log, I have a SingletonScriptableObject issue, maybe its not related with SceneReference asset. I am looking into it now, will give you a feedback soon.

**Comment by Buffoverflow** [comment]
yes, its not related with SceneReference guys, sorry :S

**Comment by starikcetin** [comment]
No worries, glad you fixed it.
