### ISSUE TITLE
Typo on tooltip for setting Show Inline Scene-In-Build Utility

### ISSUE THREAD

**Issue by hsandt** [starikcetin/Eflatun.SceneReference#21]
The tooltip for custom setting "Show Inline Scene-In-Build Utility" reads "SShould we ..." with double S.

**Comment by starikcetin** [comment]
Thank you for reporting, I will fix it soon.

**Comment by starikcetin** [comment]
Fixed in 99a796db67daede8d8d9f0e937d4889c2c9e364e. Will be included in the next release.

**Comment by starikcetin** [comment]
Included in [`1.3.0`](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/1.3.0).
