### ISSUE TITLE
There's no way to check if SceneReference is assigned or not

### ISSUE THREAD

**Issue by HunterAhlquist** [starikcetin/Eflatun.SceneReference#29]
In my code I want to do this:
`if (sceneReference != null) {
   //do something
}`

However, sceneReference will never be null, and there is no property or method to check if anything has been assigned in the inspector, and HasValue or IsSafeToUse does not work for this use case. Is this intentional or am I missing something? 
In my case, I'm using scene reference to set up a map transition script. If the scene reference variable is empty, I want to just teleport the player to a spawn location of the same scene.

Doing any of the following will produce a SceneReferenceInternalException error if the inspector value is empty:
`if (sceneReference != null) {
   //do something
}`
`if (sceneReference.HasValue) {
   //do something
}`
`if (sceneReference.IsSafeToUse) {
   //do something
}`

**Comment by HunterAhlquist** [comment]
For now my work around is to use a try-catch block, but that might bypass other errors that I might want to know about since the thrown error is SceneReferenceInternalException.

**Comment by starikcetin** [comment]
The intended way for this is the use `HasValue`. There might be a bug if it is throwing `SceneReferenceInternalException`. I will investigate.

**Comment by starikcetin** [comment]
I tested it and I am not getting any exceptions from any of the if statements you have written, everything is working as expected. Can you prepare a minimally verifiable sample project for me to look at?

**Comment by starikcetin** [comment]
Hello @HunterAhlquist are still having this issue?

**Comment by HunterAhlquist** [comment]
Hi, sorry I've been working hard on finishing my own project. I'm testing it today on a fresh project.

**Comment by HunterAhlquist** [comment]
Gave it all a test on a fresh 2020.3.43 Unity project. I used this test script (SceneReferenceTest.cs) on the camera object of the template scene, leaving the variable empty:
```using Eflatun.SceneReference;
using UnityEngine;

public class SceneReferenceTest : MonoBehaviour {
    public SceneReference scene;
    // Start is called before the first frame update
    void Start()
    {
        if (scene.HasValue) {
            Debug.Log("not null");
        }
        else {
            Debug.Log("null");
        }
    }
}
```
It returned this stack-trace:
```
SceneReferenceInternalException: [Eflatun.SceneReference] If you are seeing this, something has gone wrong internally. Please open an issue on Github (https://github.com/starikcetin/Eflatun.SceneReference/issues) and include the following information:
Location: 54783205
Info: AssetGuidHex is invalid. AssetGuidHex: ""
Eflatun.SceneReference.SceneReference.get_HasValue () (at Library/PackageCache/com.eflatun.scenereference@928ac7f606/Runtime/SceneReference.cs:112)
SceneReferenceTest.Start () (at Assets/SceneReferenceTest.cs:9)
```
I can't attach my project because Unity projects are always super bloated.

**Comment by HunterAhlquist** [comment]
Here's an external link to my project: https://1drv.ms/u/s!Asm7qfyxvd1Lgp16CnmCbLpmhKmrrg?e=GPOhaF

**Comment by starikcetin** [comment]
Thank you, I will give it a look and get back to you.

**Comment by starikcetin** [comment]
Fixed in [1.4.1](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/1.4.1).

**Comment by nehvaleem** [comment]
Sorry for commenting on a closed issue @starikcetin, but I found the same problem, but for me the `Eflatun.SceneReference.SceneReference.HasValue` is private (the same as in this repository). Did I get something wrong here?

**Comment by starikcetin** [comment]
@nehvaleem I am not sure I quite understand. Are you simply trying to check if a SceneReference has something assigned? If so, you should use the [validation API](https://github.com/starikcetin/Eflatun.SceneReference?tab=readme-ov-file#validation).
