### ISSUE TITLE
[Feature] Adding to Scene Reference List via Script

### ISSUE THREAD

**Issue by safamai** [starikcetin/Eflatun.SceneReference#32]
Planning to create some editor tools to get all scenes from a "directory" & want to add list to the scene reference list

**Comment by starikcetin** [comment]
Implemented in #34. Will be included in the next release.

**Comment by starikcetin** [comment]
Included in [1.5.0](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/1.5.0).
