### ISSUE TITLE
If you are seeing this, something has gone wrong internally

### ISSUE THREAD

**Issue by johankitti** [starikcetin/Eflatun.SceneReference#33]
Hello!

I'm using your excellent SceneReference in a project and I'm getting this error. I have a scene field that is optional and I get this error when I try to access the scene field when no scene is selected.

`SceneReferenceInternalException: [Eflatun.SceneReference] If you are seeing this, something has gone wrong internally. Please open an issue on Github (https://github.com/starikcetin/Eflatun.SceneReference/issues) and include the following information:
Location: 54783205
Info: AssetGuidHex is invalid. AssetGuidHex: ""
Eflatun.SceneReference.SceneReference.get_HasValue () (at ./Library/PackageCache/com.eflatun.scenereference@928ac7f606/Runtime/SceneReference.cs:115)
`

Regardless of what I try to access on the class, I get the same error. HasValue, IsSafeToUse etc.

**Comment by starikcetin** [comment]
Which version are you using? There was a similar bug that was fixed in [1.4.1](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/1.4.1).

**Comment by johankitti** [comment]
Thank you for such fast reply! I'm using 1.4.0. I will try upgrading at once, thanks!

**Comment by johankitti** [comment]
Indeed that seem to solve the issue, thank you very much!
