### ISSUE TITLE
Feature Request: Add "Open Build Settings..." opion

### ISSUE THREAD

**Issue by SisusCo** [starikcetin/Eflatun.SceneReference#41]
### The Problem
I think I'd rather go to Build Settings and add the scene there manually if it's missing, so I can control it's exact placement, rather than just press the _Add to Build_ button and leave it at that.

### Potential Solutions
1. The dialog that opens when you press the _Add to Build_ button could contain an _Open Build Settings..._ option. That would be more useful for me than the _Add to Build as Disabled_ option it currently has.
2. A context menu item for opening Build Settings (EditorApplication.ExecuteMenuItem("File/Build Settings...")). The good thing about this would be that it could be used even after the _Add to Build_ button has already gone away. The downside is that it would be easy to miss this feature, as it's completely hidden.

**Comment by starikcetin** [comment]
Implemented in #42, will be included in the next release. Thank you for your suggestion.

**Comment by starikcetin** [comment]
Included in [2.1.0](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/2.1.0)
