### ISSUE TITLE
auto trigger script reload after entering play mode

### ISSUE THREAD

**Issue by eterlan** [starikcetin/Eflatun.SceneReference#45]
Thanks for your hard work! My problem is, the package would trigger script reload when entering play mode, which breaks my hot reload workflow. Remove the package would fix the problem, do you have any idea about it?

**Comment by starikcetin** [comment]
Hello, can you try disabling the `Before Enter Play Mode` generation trigger and see if that helps? [Here](https://github.com/starikcetin/Eflatun.SceneReference#generation-triggers) is the relevant documentation.

**Comment by starikcetin** [comment]
I am closing this issue as you did not respond. Feel free to ping me with the relevant information if the issue persists.
