### ISSUE TITLE
[3.1.0] [Unity 2022.3.4f1] Trying to open project settings generates errors and draws an empty panel

### ISSUE THREAD

**Issue by Selmar** [starikcetin/Eflatun.SceneReference#59]
See below image. I've tried to reset all settings I can find and remove the library folder, but it keeps popping up. Did you see this before?

`Unity 2022.3.4f1`
added package dependency with `git+https://github.com/starikcetin/Eflatun.SceneReference.git#3.1.0`

![image](https://github.com/starikcetin/Eflatun.SceneReference/assets/3010534/6aafb3bd-5494-4074-8bb9-ddc777bd2abc)

**Comment by starikcetin** [comment]
Hello, I will take a look today.

**Comment by starikcetin** [comment]
@Selmar Did this by any chance happen after upgrading from a previous version?

**Comment by Selmar** [comment]
That could be the cause, it was a new project and I added the old version first by accident.

**Comment by starikcetin** [comment]
I see. I am away from my computer for a while. In the meantime, can you try this as a temporary solution:

1. Close Unity completely
2. Delete `ProjectSettings/Packages/com.eflatun.scenereference
/Settings.json` file
3. Open Unity again
4. Reapply your `Eflatun.SceneReference` settings

**Comment by starikcetin** [comment]
I confirmed the bug happening with a fresh 3.1.0 install without an upgrade from a previous version. Will investigate very soon. Thank you for the report.

**Comment by starikcetin** [comment]
Fixed in #60, will be included in the next release.

**Comment by starikcetin** [comment]
Included in [3.1.1](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/3.1.1).

**Comment by Selmar** [comment]
Confirmed the fix, thanks!
