### ISSUE TITLE
Addressable Scene Support

### ISSUE THREAD

**Issue by Ale1** [starikcetin/Eflatun.SceneReference#6]
if scene is marked as addressable, the scenemap json generator should refresh, and save to the json the addressable key.  This will allow in runtime to then run` Addressables.LoadResourceLocationsAsync(MySceneReference.addressableKey)`, which will find you the scene in the addressable catalog and from there you can load the asset through the addressables system.

**Comment by starikcetin** [comment]
This functionality will be implemented in a separate library. Please see my comment here: https://github.com/starikcetin/Eflatun.SceneReference/pull/5#issuecomment-1204592555

**Comment by starikcetin** [comment]
Update: I am currently working on support for addressable scenes. No ETA yet.

**Comment by starikcetin** [comment]
Implemented in #47. Will be included in next release.

**Comment by starikcetin** [comment]
Included in [3.0.0](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/3.0.0).
