### ISSUE TITLE
Suggestion: Toolbox doesn't need a title bar

### ISSUE THREAD

**Issue by lucasmontec** [starikcetin/Eflatun.SceneReference#62]
The toolbox can be simpler, just a simple drop-down with items aligned to the left and no title.
Just a suggestion, so it feels more like normal unity.

**Comment by starikcetin** [comment]
I appreciate your suggestion. 

I put the title there deliberately. If someone needs help with the tools, I don't want them to be confused about where they are coming from. The title helps in that regard. I also plan to add more things there in the future. It won't be just a dropdown, but rather an actual toolbox. Therefore I will keep the title for now.

I will experiment with the left alignment and see if things look better that way.
