### ISSUE TITLE
GenerationTriggers not rendering in Project Settings inspector (2022.3)

### ISSUE THREAD

**Issue by HG-Dev** [starikcetin/Eflatun.SceneReference#63]
Something about the SceneDataMapsGeneratorTriggers enum isn't sitting well with the Editor settings window: while the GenerationTriggers user setting field is set to be rendered (i.e. its attribute is not commented out), an `IndexOutOfRangeException` and `InvalidCastException` occur, and the entire settings menu fails to render. This occurs both on Windows and Mac, in 2022.3.

<img width="1093" alt="image" src="https://github.com/starikcetin/Eflatun.SceneReference/assets/29112495/0a2e8987-b23b-410c-8455-82f585bb947b">

**Comment by starikcetin** [comment]
Which version are you using? A similar bug was fixed in 3.1.1.

**Comment by HG-Dev** [comment]
Ah-ha. I thought I was using the latest version, but it was set at 3.1.0 in the manifest.
Updating fixed both this and an error on startup related to addressables.
Thanks!

**Comment by HG-Dev** [comment]
Non-issue!

**Comment by starikcetin** [comment]
@HG-Dev What was the error on startup regarding addressables?

**Comment by HG-Dev** [comment]
I'm not 100% sure on the specifics, but it likely has something to do with how when the addressables package is imported but unconfigured, you get the following errors (even in the latest version):
```
System.NullReferenceException: Object reference not set to an instance of an object
  at Eflatun.SceneReference.Editor.MapGeneratorTriggers.AddressablesChangeListener..cctor () [0x00000] in C:\R\dmo-ProTheme-UIKit\Library\PackageCache\com.eflatun.scenereference@c94f1c9902\Editor\MapGeneratorTriggers\AddressablesChangeListener.cs:14 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes (System.Type[])
```
```
ArgumentException: Value does not fall within the expected range.
Eflatun.SceneReference.Editor.SceneDataMapsGenerator.GenerateSceneGuidToAddressMap (System.String[] allSceneGuids) (at Library/PackageCache/com.eflatun.scenereference@c94f1c9902/Editor/SceneDataMapsGenerator.cs:79)
```
This might merit its own issue.

**Comment by starikcetin** [comment]
Thank you. Yes, it is tracked here: #65
