### ISSUE TITLE
Adding this repo as a submodule is not possible because it's a whole Unity project

### ISSUE THREAD

**Issue by MeisterDerMagie** [starikcetin/Eflatun.SceneReference#69]
Hello there,

the title says it all: We prefer to add utility tools like SceneReference as submodules to our Core-repository. That's only possible if the repo is not a full blown Unity project with assets, meta files and stuff. Is there a reason why this repo is not just the SceneReference code? This would make it much easier for us to add and maintain this repo.

**Comment by Ale1** [comment]
Have you tried pointing to the package folder instead of the root of the project ?  e.g: 

`git submodule add https://github.com/statikcetin/Eflatun.SceneReference/Packages/com.eflatun.scenereference`

That way it only brings in the package contents and not everything in assets folder.

**Comment by starikcetin** [comment]
I don't suggest this, and we will not be supporting it. However, if you really wish to do that, here is what I was doing before UPM existed:

1. Place the submodule somewhere outside `Assets`.
2. Symlink the package source folder from within the submodule to within `Assets`.
