### ISSUE TITLE
Continuous NullReferenceException when Addressables Settings not initialised

### ISSUE THREAD

**Issue by mgmhunt** [starikcetin/Eflatun.SceneReference#71]
Initially thought it was an incompatability with Odin Inspector.

Uninstalling Addressables package worked to stop the continuous logging.

But found out it was because I hadn't initialised Addressable Settings yet - ie the package was installed but I haven't got round to using it yet in the Project.

Maybe a check needed somewhere.

`[Exception] NullReferenceException: Object reference not set to an instance of an object
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
Rethrow as OdinPropertyException: This error occurred while being drawn by Odin.
Current IMGUI event: repaint
Odin Property Path: worldScene
Odin Drawer Chain:
> PropertyContextMenuDrawer<SceneReference>
> ReferenceDrawer<SceneReference>
> FixUnityNullDrawer<SceneReference>
> NullableReferenceDrawer<SceneReference>
> UnityPropertyDrawer<SceneReferencePropertyDrawer, SceneReference>
> CompositeDrawer.
SceneReferencePropertyDrawer.Init() at Library/PackageCache/com.eflatun.scenereference@c94f1c9902/Editor/SceneReferencePropertyDrawer.cs:84

SceneReferencePropertyDrawer.OnGUI() at Library/PackageCache/com.eflatun.scenereference@c94f1c9902/Editor/SceneReferencePropertyDrawer.cs:129

PropertyDrawer.OnGUISafe() at /Users/bokken/build/output/unity/unity/Editor/Mono/ScriptAttributeGUI/PropertyDrawer.cs:23

PropertyHandler.OnGUI() at /Users/bokken/build/output/unity/unity/Editor/Mono/ScriptAttributeGUI/PropertyHandler.cs:170

PropertyHandler.OnGUI() at /Users/bokken/build/output/unity/unity/Editor/Mono/ScriptAttributeGUI/PropertyHandler.cs:131

RuntimeMethodInfo.Invoke() at <b476499a37ba4db68de311f404f49770>:0

UnityPropertyHandlerUtility.PropertyHandlerOnGUI() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Value Drawers/UnityPropertyHandlerUtility.cs:216

Sirenix.OdinInspector.Editor.UnityPropertyDrawer`2[TDrawer,TDrawnType].DrawPropertyLayout() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Value Drawers/UnityPropertyDrawer.cs:127

OdinDrawer.CallNextDrawer() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:155

Sirenix.OdinInspector.Editor.Drawers.NullableReferenceDrawer`1[T].DrawPropertyLayout() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Misc Drawers/NullableReferenceDrawer.cs:113

OdinDrawer.CallNextDrawer() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:155

Sirenix.OdinInspector.Editor.Drawers.FixUnityNullDrawer`1[T].DrawPropertyLayout() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Misc Drawers/FixUnityNullDrawer.cs:87

OdinDrawer.CallNextDrawer() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:155

Sirenix.OdinInspector.Editor.Drawers.ReferenceDrawer`1[T].DrawPropertyLayout() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Misc Drawers/ReferenceDrawer.cs:118

OdinDrawer.CallNextDrawer() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:155

Sirenix.OdinInspector.Editor.Drawers.PropertyContextMenuDrawer`1[T].DrawPropertyLayout() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Misc Drawers/PropertyContextMenuDrawer.cs:659

OdinDrawer.DrawProperty() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:109

InspectorProperty.Draw() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/InspectorProperty.cs:849

Debug.LogException()

InspectorProperty.Draw() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/InspectorProperty.cs:926

InspectorProperty.Draw() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/InspectorProperty.cs:737

UnityObjectRootDrawer`1.DrawPropertyLayout() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Value Drawers/UnityObjectRootDrawer.cs:60

OdinDrawer.CallNextDrawer() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:155

FixBrokenUnityObjectWrapperDrawer`1.DrawPropertyLayout() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Attribute Drawers/FixBrokenUnityObjectWrapperDrawer.cs:41

OdinDrawer.DrawProperty() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:109

InspectorProperty.Draw() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/InspectorProperty.cs:849

PropertyTree.DrawProperties() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/PropertyTree.cs:552

PropertyTree.Draw() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/PropertyTree.cs:444

OdinEditor.DrawTree() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinEditor.cs:97

OdinEditor.DrawOdinInspector() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinEditor.cs:254

OdinEditor.OnInspectorGUI() at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinEditor.cs:79

GUIUtility.ProcessEvent() at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189
`

**Comment by starikcetin** [comment]
Fixed in #78. Will be included in the next release.

**Comment by starikcetin** [comment]
Included in [3.1.3](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/3.1.3).
