### ISSUE TITLE
[BUG] 'EditorStyles' does not contain a definition for 'iconButton' in Unity 2020

### ISSUE THREAD

**Issue by dlfanx** [starikcetin/Eflatun.SceneReference#74]
Affected script: https://github.com/starikcetin/Eflatun.SceneReference/blob/8e449ce4d162e4061f8d23af47cf5d814dbdd15a/Eflatun.SceneReference/Packages/com.eflatun.scenereference/Editor/SceneReferencePropertyDrawer.cs#L167C5-L167C5

Can be replaced with https://docs.unity3d.com/2020.3/Documentation/ScriptReference/EditorStyles-miniButton.html

**Comment by starikcetin** [comment]
Thank you for the bug report. I would be happy to accept a PR for this.

**Comment by Ale1** [comment]
@starikcetin, @dlfanx .  check out PR #75

**Comment by starikcetin** [comment]
Fixed in #76. Will be included in the next release.

**Comment by starikcetin** [comment]
Included in [3.1.2](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/3.1.2).
