### ISSUE TITLE
Move RunSceneGUIDToPathMapGenerator MenuItem to Tools tab

### ISSUE THREAD

**Issue by Artein** [starikcetin/Eflatun.SceneReference#9]
Right now MenuItem RunSceneGUIDToPathMapGenerator locates at "Eflatun/Scene Reference".
But Unity projects often have a lot of packages and the toolbar becomes too big.

Would be nice to move the location of the MenuItem under the Tools tab.
For example, "Tools/Eflatun Scene Reference/RunSceneGUIDToPathMapGenerator".

**Comment by starikcetin** [comment]
That is a good idea. I will implement it when I get the chance.

**Comment by starikcetin** [comment]
Thank you for your suggestion @Artein. I merged the change to main branch. It will be included in the next release.

**Comment by starikcetin** [comment]
Included in [1.2.0](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/1.2.0).
