### ISSUE TITLE
Color Based On Scene-In-Build State Exceptions

### ISSUE THREAD

**Issue by mgmhunt** [starikcetin/Eflatun.SceneReference#98]
Minor feature request

At the moment 'Color Based On Scene-In-Build State' is a overall setting that highlights whether a scene is in the build or not.

I have a Scene Reference that is not in the build as it's for editor purposes only, but it highlights red in the Inspector.  It would be great to be able to add this scene to an 'exceptions' list. Via preferences and using the Scene Reference Toolbox dropdown menu.

**Comment by starikcetin** [comment]
Sensible. I'll see what we can do.

**Comment by starikcetin** [comment]
Implemented in #103. Will be included in the next release.

**Comment by starikcetin** [comment]
Included in [4.1.0](https://github.com/starikcetin/Eflatun.SceneReference/releases/tag/4.1.0).
